### PR TITLE
Fix #9 Missing eslint from npm isntall

### LINKED ISSUE #9: Setup does not work without having eslint installed
We need to add eslint as a development dependency to the setup, like this:

`npm install --save-dev eslint-config-hyperoslo eslint-config-airbnb eslint`

### PR DESCRIPTION
**Pull request by ohenrik**

### CODE REVIEW

**Comment by timkurvers** [comment]
https://github.com/hyperoslo/eslint-config/pull/11 :smile:

**Comment by sindrenm** [comment]
Haha! :grinning:

**Comment by sindrenm** [comment]
Also, it's a small thing, and I don't know if we have a policy on this, but I'd prefer if we didn't reference GitHub issue numbers in commit messages, due to the fact that they are meaningless in any other context. It's nice to reference the GitHub issue in the PR, but that can be done in the issue description (like in #11), which unties it from the commit itself. :smiley:

**Comment by sindrenm** [comment]
Will close this as #11 is merged. Thanks, @ohenrik. :smiley:

**Comment by ohenrik** [comment]
loooool

**Comment by ohenrik** [comment]
Haha, should check if there already is a PR i guess
:p

**Pull request closed without merging**
